# Generated by Django 4.0.3 on 2022-04-01 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=160)),
                ('address', models.TextField(max_length=50)),
                ('featured', models.BooleanField(blank=True)),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Amenity')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media', verbose_name='Picture')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50, verbose_name='Property Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=99999999999, verbose_name='Price')),
                ('property_description', models.TextField(max_length=160, verbose_name='Description')),
                ('date_listed', models.DateField(blank=True)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('R', 'Rent'), ('S', 'Sale'), ('L', 'Lease')], max_length=2)),
                ('featured', models.BooleanField()),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('no_of_plots', models.IntegerField(verbose_name='Plots')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.agent')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.amenity')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.images')),
            ],
            options={
                'ordering': ['date_listed'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50, verbose_name='Property Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=99999999999, verbose_name='Price')),
                ('property_description', models.TextField(max_length=160, verbose_name='Description')),
                ('date_listed', models.DateField(blank=True)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('R', 'Rent'), ('S', 'Sale'), ('L', 'Lease')], max_length=2)),
                ('featured', models.BooleanField()),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('no_of_bedroom', models.PositiveIntegerField(verbose_name='Bed')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.agent')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.amenity')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.images')),
            ],
            options={
                'ordering': ['date_listed'],
                'abstract': False,
            },
        ),
    ]
