# Generated by Django 4.0.3 on 2022-04-12 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=160)),
                ('address', models.TextField(max_length=50)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Amenity')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50, verbose_name='Property Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=99999999999, verbose_name='Price')),
                ('property_description', models.TextField(max_length=160, verbose_name='Description')),
                ('date_listed', models.DateField(auto_now_add=True)),
                ('state', models.CharField(blank=True, default='Kwara', max_length=20)),
                ('city', models.CharField(blank=True, default='Ilorin', max_length=20)),
                ('area', models.CharField(blank=True, default='MFM', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Lease', 'Lease')], max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('no_of_plots', models.IntegerField(blank=True, default=2, verbose_name='Plots')),
                ('no_of_bedroom', models.PositiveIntegerField(verbose_name='Bed')),
                ('no_of_bathroom', models.PositiveIntegerField(blank=True, default=1, verbose_name='Bathroom')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.agent')),
                ('amenity', models.ManyToManyField(to='realEstate.amenity')),
            ],
            options={
                'ordering': ['date_listed'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50, verbose_name='Property Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=99999999999, verbose_name='Price')),
                ('property_description', models.TextField(max_length=160, verbose_name='Description')),
                ('date_listed', models.DateField(auto_now_add=True)),
                ('state', models.CharField(blank=True, default='Kwara', max_length=20)),
                ('city', models.CharField(blank=True, default='Ilorin', max_length=20)),
                ('area', models.CharField(blank=True, default='MFM', max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Lease', 'Lease')], max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('no_of_plots', models.IntegerField(blank=True, default=2, verbose_name='Plots')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.agent')),
                ('amenity', models.ManyToManyField(to='realEstate.amenity')),
            ],
            options={
                'ordering': ['date_listed'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='house_image', verbose_name='Picture')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.house')),
            ],
        ),
    ]
