# Generated by Django 4.0.3 on 2022-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0002_alter_house_image_alter_land_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(blank=True, default='Ilorin', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='state',
            field=models.CharField(blank=True, default='Kwara', max_length=20),
        ),
        migrations.AddField(
            model_name='land',
            name='city',
            field=models.CharField(blank=True, default='Ilorin', max_length=20),
        ),
        migrations.AddField(
            model_name='land',
            name='state',
            field=models.CharField(blank=True, default='Kwara', max_length=20),
        ),
    ]
