# Generated by Django 4.0.3 on 2022-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0003_house_city_house_state_land_city_land_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
        migrations.RemoveField(
            model_name='land',
            name='location',
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, default='36, MFM Junction', max_length=50),
        ),
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='land',
            name='address',
            field=models.CharField(blank=True, default='36, MFM Junction', max_length=50),
        ),
        migrations.AddField(
            model_name='land',
            name='area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Lease', 'Lease')], max_length=10),
        ),
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Lease', 'Lease')], max_length=10),
        ),
    ]
