# Generated by Django 4.0.3 on 2022-04-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0005_alter_house_area_alter_land_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='amenity',
        ),
        migrations.AddField(
            model_name='house',
            name='amenity',
            field=models.ManyToManyField(to='realEstate.amenity'),
        ),
        migrations.RemoveField(
            model_name='house',
            name='image',
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.ManyToManyField(blank=True, to='realEstate.images'),
        ),
        migrations.RemoveField(
            model_name='land',
            name='amenity',
        ),
        migrations.AddField(
            model_name='land',
            name='amenity',
            field=models.ManyToManyField(to='realEstate.amenity'),
        ),
        migrations.RemoveField(
            model_name='land',
            name='image',
        ),
        migrations.AddField(
            model_name='land',
            name='image',
            field=models.ManyToManyField(blank=True, to='realEstate.images'),
        ),
    ]
