# Generated by Django 4.0.3 on 2022-04-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0008_alter_agent_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
