# Generated by Django 4.0.3 on 2022-04-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0009_agent_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='images',
            name='picture',
            field=models.ImageField(upload_to='house_image', verbose_name='Picture'),
        ),
    ]
