# Generated by Django 4.0.3 on 2022-04-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0010_alter_agent_profile_picture_alter_images_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='date_listed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='date_listed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
