# Generated by Django 4.0.3 on 2022-04-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0012_alter_house_featured_alter_land_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.IntegerField(blank=True, verbose_name='Phone Number'),
        ),
    ]
