# Generated by Django 4.0.3 on 2022-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0014_alter_agent_phone_number_alter_agent_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_picture'),
        ),
    ]
