# Generated by Django 4.0.3 on 2022-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0015_alter_agent_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ManyToManyField(to='realEstate.images'),
        ),
        migrations.AlterField(
            model_name='land',
            name='image',
            field=models.ManyToManyField(to='realEstate.images'),
        ),
    ]
